### ISSUE TITLE
Add Melanie-Jane Manley to IBM-Bluemix-Docs/Predictive Modeling

### ISSUE THREAD

**Issue by msochka** [IBM-Bluemix-Docs/PredictiveModeling#3]
Melanie is now working on the Watson Machine Learning tasks and needs access to this repo.

@mjmanley @kKronstainBrown @sefuhrer 

Please add Melanie. Thanks

**Comment by kKronstainBrown** [comment]
@msochka Melanie already has write access, but since you are an admin, you can change her role in the future from the Settings > Collaborators & teams tab if you like.

**Comment by msochka** [comment]
Thanks!
