### ISSUE TITLE
Add Sarah Packowski to IBM-Bluemix-Docs/PredictiveModeling GitHub repo

### ISSUE THREAD

**Issue by msochka** [IBM-Bluemix-Docs/PredictiveModeling#4]
@sefuhrer @kKronstainBrown @spackows

Sarah Packowski needs to be added to this repo as a Content Designer.

**Comment by kKronstainBrown** [comment]
@msochka Added her, but since you are an admin, you can do it yourself in the future from the Settings > Collaborators & teams tab.

**Comment by msochka** [comment]
Thanks!
