### ISSUE TITLE
WML View Docs links to an outdated PredictiveModeling page

### ISSUE THREAD

**Issue by kwright15** [IBM-Bluemix-Docs/PredictiveModeling#5]
Clicking on View Docs from the WML catalog page (https://cloud.ibm.com/catalog/services/machine-learning) links to this outdated page: https://console.bluemix.net/docs/services/PredictiveModeling/index.html#WMLgettingstarted
And when you click on the "latest documentation" link it takes you to another page that makes no sense: https://cloud.ibm.com/docs/services/PredictiveModeling?topic=PredictiveModeling-WMLgettingstarted#WMLgettingstarted

**Comment by spackows** [comment]
Yes, work is already under way to change the "view docs" link and get rid of those old pages.
Closing as duplicate.
